service: aws-lambda-puppeteer-serverless

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::webscraper-failsafe/*"

plugins:
  - serverless-offline


functions:
  puppeteerExample:
    handler: run_puppeteer.handler

